llm:
  provider: google
  config:
    model: gemini-flash-1.5
    max_tokens: 10000
    temperature: 0.5
    top_p: 1
    stream: false

embedder:
  provider: google
  config:
    model: 'models/embedding-001'
    task_type: "retrieval_document"
    title: "Embeddings for Embedchain"
